
name: create account

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
  

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 17.x

    - run: npm install
    - run: npm run cy:run
      continue-on-error: true
    
    - run: npm run report:merge
    
    - run: npm run report:mocha


    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages1
        FOLDER: mochawesome-report
